name: Deploy UserService Backend

on:
  push:
    branches:
      - main
    paths:
      - 'src/userservice/backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/Weefly-Transactionservice/src/userservice/backend

            # Discard any local changes that would block git pull
            git reset --hard HEAD

            # Pull latest changes from repo
            git pull origin main

            # Fix file permissions
            sudo chown -R ubuntu:ubuntu .
            chmod -R u+rw .

            # Install dependencies
            npm install

            # Restart the app with PM2
            pm2 delete user-service || true
            pm2 start npm --name "user-service" -- run prod
          EOF
